language: java
sudo: false
script: mvn clean verify -Pskip-ui-tests
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true   
  file: "${HOME}/build/${TRAVIS_REPO_SLUG}/net.resheim.eclipse.launcher-site/target/net.resheim.eclipse.launcher-*.zip"
  api_key:
    secure: iVJL4mNY5GG6o32foel+hVV6wDgfg6uMi2G5iHd3lzDdhgtrkqeWcfdJu/gVl7MmQiJzevnnBFbOLpsvXj0RDMEuYWszrnf9ke87P8vqMvpMkoDRHh9z0gaEq4pnsb4BQMxdU+RYOvbXZc7VKuChwxyT5TX35XWZbIJtVyBwaa0=
  on:
    repo: turesheim/eclipse-launcher
    tags: true
    all_branches: true
